default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: 132516
  host: localhost
  port: 5432

development:
  <<: *default
  database: SNDatabase_dev

test:
  <<: *default
  database: SNDatabase_test

production:
  <<: *default
  role: MyRole
